### PR TITLE
Masked image disapear on resolution change bug fix

### PR DESCRIPTION
**Pull request by Luanrobs**
---
name: Pull Request
about: Create a pull request
title: ''
assignees: mob-sakai

---

**NOTE: Create a pull request to merge into `develop` branch**

### CODE REVIEW

**Comment by Firnu** [comment]
Would be great to have this pulled to the main package.

**Review by dmlucas — APPROVED** [review]

**Comment by jarettgross** [comment]
@mob-sakai Would you be able to merge this PR? It'd be very helpful to get this fixed.

**Comment by flowerhouse-dev** [comment]
@mob-sakai I would also really like to see this merged.

**Comment by mob-sakai** [comment]
Sorry for my late reply.
Thank you for your cooperation!

**Pull request merged**
